### ISSUE TITLE
DX: zero dependency

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/finalize#2]
to ease use in a project which already contains rector and/or phpstan it would be great this tool would be shipped as a zero-dependency CLI tool

**Comment by TomasVotruba** [comment]
Wait a bit with issues here, as this is still WIP package. There are dozens of ideas, but I want to keep this repository clean untill I release it officialy.

Take it as a VIP access :) 

PR are welcomed though :+1:  Thanks :heart:
